TOOL_REGISTRY_SEED = [
    {
        "name": "Cursor",
        "category": "IDE",
        "description": "AI-first code editor with deep repo understanding and agentic workflows.",
        "is_free": False,
        "official_url": "https://cursor.com",
        "supported_prompt_platforms": ["Cursor", "Claude Code"],
    },
    {
        "name": "Claude Code",
        "category": "IDE",
        "description": "Terminal-native coding agent by Anthropic for autonomous development tasks.",
        "is_free": False,
        "official_url": "https://docs.anthropic.com/en/docs/claude-code",
        "supported_prompt_platforms": ["Claude Code", "Cursor"],
    },
    {
        "name": "Windsurf",
        "category": "IDE",
        "description": "Agentic IDE with cascading edits across the entire codebase.",
        "is_free": True,
        "official_url": "https://codeium.com/windsurf",
        "supported_prompt_platforms": ["Windsurf", "Cursor"],
    },
    {
        "name": "Bolt",
        "category": "IDE",
        "description": "Browser-based AI app builder for rapid prototyping with live previews.",
        "is_free": True,
        "official_url": "https://bolt.new",
        "supported_prompt_platforms": ["Bolt", "Lovable"],
    },
    {
        "name": "Lovable",
        "category": "IDE",
        "description": "AI-powered full-stack app builder with visual editing and deployment.",
        "is_free": False,
        "official_url": "https://lovable.dev",
        "supported_prompt_platforms": ["Lovable", "Bolt"],
    },
    {
        "name": "Replit",
        "category": "IDE",
        "description": "Cloud IDE with integrated AI agent for building and deploying apps.",
        "is_free": True,
        "official_url": "https://replit.com",
        "supported_prompt_platforms": ["Replit", "Bolt"],
    },
    {
        "name": "Vercel",
        "category": "Deployment",
        "description": "Zero-config deployment platform optimized for frontend frameworks.",
        "is_free": True,
        "official_url": "https://vercel.com",
        "supported_prompt_platforms": ["Cursor", "Claude Code", "Windsurf"],
    },
    {
        "name": "Fly.io",
        "category": "Deployment",
        "description": "Run full-stack applications close to users with global regions.",
        "is_free": False,
        "official_url": "https://fly.io",
        "supported_prompt_platforms": ["Cursor", "Claude Code"],
    },
    {
        "name": "Cloudflare Workers",
        "category": "Deployment",
        "description": "Serverless edge functions deployed across 300+ points of presence.",
        "is_free": True,
        "official_url": "https://workers.cloudflare.com",
        "supported_prompt_platforms": ["Cursor", "Claude Code", "Windsurf"],
    },
    {
        "name": "Supabase",
        "category": "Database",
        "description": "Postgres platform with auth, storage, realtime, and row-level security.",
        "is_free": True,
        "official_url": "https://supabase.com",
        "supported_prompt_platforms": ["Cursor", "Claude Code", "Lovable"],
    },
    {
        "name": "Neon",
        "category": "Database",
        "description": "Serverless Postgres with instant branching for preview environments.",
        "is_free": True,
        "official_url": "https://neon.tech",
        "supported_prompt_platforms": ["Cursor", "Claude Code"],
    },
    {
        "name": "PlanetScale",
        "category": "Database",
        "description": "MySQL-compatible database with schema branching and horizontal scaling.",
        "is_free": False,
        "official_url": "https://planetscale.com",
        "supported_prompt_platforms": ["Cursor", "Claude Code"],
    },
    {
        "name": "GitHub Copilot",
        "category": "IDE",
        "description": "AI pair programmer integrated into VS Code, JetBrains, and GitHub.",
        "is_free": False,
        "official_url": "https://github.com/features/copilot",
        "supported_prompt_platforms": ["Cursor", "Windsurf"],
    },
    {
        "name": "Emergence AI",
        "category": "Backend",
        "description": "AI infrastructure platform for deploying and orchestrating agent workflows.",
        "is_free": False,
        "official_url": "https://www.emergence.ai",
        "supported_prompt_platforms": ["Claude Code", "Cursor"],
    },
]
